name: "Semgrep: Auditoría Mensual Completa"

on:
  schedule:
    # Se ejecuta a las 00:00 el día 1 de cada mes
    - cron: '0 0 1 * *'
  workflow_dispatch: {} # Permite lanzarlo manualmente si sospechas de algo

jobs:
  semgrep-full-scan:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Full Scan
        # Ejecuta todas las reglas en todo el proyecto
        run: semgrep ci
